version: "3"
services:
  phpttpd:
    build: .
    container_name: httpd
    ports:
      - "4507:443"
      - "4508:80"
    volumes:
      - ./www/public:/usr/local/apache2/htdocs/
      - ./conf/apache2/httpd-foreground:/usr/local/bin/httpd-foreground
      - ./conf/apache2/vhosts.conf:/usr/local/apache2/conf/extra/httpd-vhosts.conf
      - ./conf/apache2/httpd-ssl.conf:/usr/local/apache2/conf/extra/httpd-ssl.conf
      - ./conf/apache2/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./conf/apache2/cert:/usr/local/apache2/conf/cert
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./conf/php/www.conf:/etc/php7/php-fpm.d/www.conf
      - ./logs/apache2:/var/log/apache2
      - ./logs/php:/usr/local/var/log:rw
    networks:
      - net-mysql
    restart: always

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - net-mysql
    ports:
      - "13306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: duanshuo@45a201681de1
      MYSQL_DATABASE: ds
      MYSQL_USER: hnrr
      MYSQL_PASSWORD: duanshuo@2020
    restart: always

networks:
  net-mysql:
