FROM php:7.2-apache 
LABEL maintainer="stone <zm3345@126.com>" version="1.0"

##
# ---------- env settings ----------
##

# --build-arg timezone=Asia/Shanghai
ARG timezone
# pdt pre test dev
ARG app_env=pdt
ARG add_user=www

ENV APP_ENV=${app_env:-"pdt"} \
    TIMEZONE=${timezone:-"Asia/Shanghai"} \
    #  install and remove building packages
    PHPIZE_DEPS="autoconf dpkg-dev dpkg file g++ gcc libc-dev make php7-dev php7-pear pkgconf re2c pcre-dev zlib-dev"

##
# ---------- building ----------
##

RUN set -ex \
        # change apk source repo
        && sed -i 's/dl-cdn.alpinelinux.org/mirrors.ustc.edu.cn/' /etc/apk/repositories \
        && apk update \
        && apk add --no-cache \
        # Install base packages
        vim \
        wget \
        net-tools \
        git \
        zip \
        unzip \
        ca-certificates \
        curl \
        tar \
        xz \
        libressl \
        # openssh  \
        openssl  \
        tzdata \
        pcre \
        #
        # install php7 and some extensions
        php7 \
        php7-common \
        php7-fpm \
        php7-amqp \
        php7-bz2 \
        php7-bcmath \
        php7-calendar \
        php7-curl \
        php7-cgi \
        php7-ctype \
        php7-dom \
        #php7-dba \
        #php7-doc \
        #php7-embed \
        #php7-enchant \
        php7-exif \
        php7-ftp \
        php7-fileinfo \
        # php7-filter \
        php7-gd \
        php7-gettext \
        php7-gmp \
        php7-iconv \
        php7-imap \
        php7-intl \
        php7-json \
        php7-ldap \
        #php7-litespeed \
        php7-memcached \
        php7-mcrypt \
        php7-mbstring \
        php7-mongodb \
        php7-mysqlnd \
        php7-mysqli \
        php7-odbc \
        php7-openssl \
        php7-opcache \
        php7-pcntl \
        php7-pdo \
        php7-pdo_dblib \
        php7-pdo_mysql \
        php7-pdo_odbc \
        php7-pdo_pgsql \
        php7-pdo_sqlite \
        php7-pgsql \
        php7-phar \
        php7-phpdbg \
        php7-pspell \
        php7-posix \
        php7-recode \
        php7-redis \
        php7-simplexml \
        # php7-sqlite \
        php7-session \
        php7-shmop \
        php7-snmp \
        php7-sockets \
        php7-soap \
        php7-sqlite3 \
        php7-ssh2 \
        php7-sysvshm \
        php7-sysvmsg \
        php7-sysvsem \
#        php7-timezonedb \
        php7-tidy \
        php7-tokenizer \
        php7-wddx \
        php7-xml \
        php7-xmlreader \
        php7-xmlrpc \
        php7-xmlwriter \
        php7-xsl \
        php7-zip \
        php7-zlib \
        && apk del --purge *-dev
##        && rm -rf /var/cache/apk/* /tmp/* /usr/share/man /usr/share/php7

##
# ---------- some config,clear work ----------
##
RUN set -ex \
        && cd /etc/php7 \
        # - config PHP
        && { \
            echo "upload_max_filesize=100M"; \
            echo "post_max_size=108M"; \
            echo "memory_limit=1024M"; \
            echo "date.timezone=${TIMEZONE}"; \
        } | tee conf.d/99-overrides.ini \
        #
        # - config timezone
        && ln -sf /usr/share/zoneinfo/${TIMEZONE} /etc/localtime \
        && echo "${TIMEZONE}" > /etc/timezone \
        #
        # ---------- some config work ----------
        # - ensure 'www' user exists
        && addgroup -S ${add_user} \
        && adduser -D -S -G ${add_user} ${add_user} \
        #
        # - create user dir
        && mkdir -p /data \
        && chown -R ${add_user}:${add_user} /data \
        && mkdir -p /usr/local/etc/ \
        && ln -s /etc/php7/php-fpm.conf /usr/local/etc/php-fpm.conf \
        && ln -s /etc/php7/php-fpm.d /usr/local/etc/php-fpm.d \
        #
        && echo -e "\033[42;37m Build Completed :).\033[0m\n"


COPY ./ioncube_loaders_lin_x86-64.tar.gz /tmp

RUN cd /tmp \
    && tar -xvzf ioncube_loaders_lin_x86-64.tar.gz -C /tmp \
    && cp ioncube/ioncube_loader_lin_7.2.so  /usr/lib/php7/modules/ioncube.so \
    && rm -Rf ioncube.tar.gz ioncube \
    && echo "zend_extension=ioncube.so" > /etc/php7/conf.d/00_ioncube.ini

EXPOSE 9000
VOLUME ["/var/www", "/data"]
WORKDIR "/var/www"

CMD /run.sh
