version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "4507:80"
    volumes:
      - ./www/public:/var/www/html/public:rw
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/conf.d:/etc/nginx/conf.d:ro
      - ./logs/nginx:/var/log/nginx:rw
    networks:
      - net-php
    restart: always
    command: nginx -g 'daemon off;'

  php:
    image: php:7.2-fpm-alpine
    container_name: php
    volumes:
      - ./www:/var/www/html:rw
      - ./conf/php/php.ini:/usr/local/etc/php/php.ini:ro
      - ./logs/php:/usr/local/var/log:rw
    expose:
      - "9000"
    networks:
      - net-php
      - net-mysql
    restart: always
    command: php-fpm

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./conf/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/mysql:/var/lib/mysql:rw
    networks:
      - net-mysql
    environment:
      MYSQL_ROOT_PASSWORD: duanshuo@45a201681de1
      MYSQL_DATABASE: ds
      MYSQL_USER: hnrr
      MYSQL_PASSWORD: duanshuo@2020
    restart: always
    command: "--character-set-server=utf8"

networks:
  net-php:
  net-mysql:
