version: '3'

services:
  oracle-db:
    image: oracleinanutshell/oracle-xe-11g
    environment:
      - ORACLE_ALLOW_REMOTE:true
      - ORACLE_DISABLE_ASYNCH_IO:true
    volumes:
      - /opt/docker/oracle/data:/u01/app/oracle/
    ports:
      - 1521:1521
      - 5500:5500