version: '3.7'

services:
  db:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL=admin@hnrr.com.cn
      PGADMIN_DEFAULT_PASSWORD=hnrradmin
    ports:
      - 5433:80

