# https://github.com/linuxserver/docker-code-server
version: "2.1"
services:
  code-server:
    image: lscr.io/linuxserver/code-server:4.8.3
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - PASSWORD=code #optional
      # - HASHED_PASSWORD= #optional
      # - SUDO_PASSWORD= #optional
      # - SUDO_PASSWORD_HASH= #optional
      # - PROXY_DOMAIN=code-server.my.domain #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
    volumes:
      - ./data/config:/config
      - /soft:/soft
    ports:
      - 8443:8443
