version: "3.1"

services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: es
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

