version: "3"
services:
  mysql:
    image: mysql:5
    container_name: mysql5
    volumes:
#    - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yzzy3306
      MYSQL_DATABASE: ry-vue
      MYSQL_USER: yzzy
      MYSQL_PASSWORD: xxgc3306
    restart: always

  redis:
    image: redis:alpine
    restart: always
    container_name: redis
    #    command: redis-server --requirepass pwd
    volumes:
      - ./data:/data
    ports:
      - 6379:6379
