version: "3"
services:

  mysql:
    image: mysql:5.7
    container_name: mysql
    volumes:
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
      - ./data/:/var/lib/mysql:rw
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: yzzy3306
      MYSQL_DATABASE: ry-vue
      MYSQL_USER: yzzy
      MYSQL_PASSWORD: xxgc3306
    restart: always

